
import { useCallback } from "react";
import { cardProcessingStages } from "../booking-flow-config";
import { resolvePositiveMinutes } from "../booking-flow.helpers";
import { usePublicBookingAvailability } from "../hooks/use-public-booking-availability";
import { usePublicBookingFlowDerived } from "../hooks/use-public-booking-flow-derived";
import { usePublicBookingIdentity } from "../hooks/use-public-booking-identity";
import { usePublicBookingLocation } from "../hooks/use-public-booking-location";
import { usePublicBookingNavigation } from "../hooks/use-public-booking-navigation";
import { usePublicBookingPaymentEffects } from "../hooks/use-public-booking-payment-effects";
import { usePublicBookingPaymentFlow } from "../hooks/use-public-booking-payment-flow";
import { usePublicBookingPaymentUi } from "../hooks/use-public-booking-payment-ui";
import { usePublicBookingServiceActions } from "../hooks/use-public-booking-service-actions";
import { usePublicBookingVoucherActions } from "../hooks/use-public-booking-voucher-actions";
import type {
  BookingFlowProps,
} from "../booking-flow.types";
import type { usePublicBookingFlowState } from "./use-public-booking-flow-state";

type Params = {
  tenant: BookingFlowProps["tenant"];
  signalPercentage: BookingFlowProps["signalPercentage"];
  publicBookingCutoffBeforeCloseMinutes: BookingFlowProps["publicBookingCutoffBeforeCloseMinutes"];
  publicBookingLastSlotBeforeCloseMinutes: BookingFlowProps["publicBookingLastSlotBeforeCloseMinutes"];
  whatsappNumber: BookingFlowProps["whatsappNumber"];
  mercadoPagoPublicKey: BookingFlowProps["mercadoPagoPublicKey"];
  state: ReturnType<typeof usePublicBookingFlowState>;
};

export function usePublicBookingFlowControllerDeps({
  tenant,
  signalPercentage,
  publicBookingCutoffBeforeCloseMinutes,
  publicBookingLastSlotBeforeCloseMinutes,
  whatsappNumber,
  mercadoPagoPublicKey,
  state,
}: Params) {
  const {
    step,
    setStep,
    selectedService,
    setSelectedService,
    isHomeVisit,
    setIsHomeVisit,
    date,
    setDate,
    selectedTime,
    setSelectedTime,
    activeMonth,
    setActiveMonth,
    clientName,
    setClientName,
    clientFirstName,
    setClientFirstName,
    clientLastName,
    setClientLastName,
    clientEmail,
    setClientEmail,
    clientPhone,
    setClientPhone,
    clientCpf,
    setClientCpf,
    acceptPrivacyPolicy,
    setAcceptPrivacyPolicy,
    acceptTermsOfService,
    setAcceptTermsOfService,
    acceptCommunicationConsent,
    setAcceptCommunicationConsent,
    isSubmitting,
    setIsSubmitting,
    appointmentId,
    setAppointmentId,
    protocol,
    setProtocol,
    clientLookupStatus,
    setClientLookupStatus,
    pixPayment,
    setPixPayment,
    pixStatus,
    setPixStatus,
    setPixError,
    pixAttempt,
    setPixAttempt,
    pixNowMs,
    setPixNowMs,
    paymentMethod,
    setPaymentMethod,
    cardStatus,
    setCardStatus,
    setCardError,
    cardAwaitingConfirmation,
    setCardAwaitingConfirmation,
    cardProcessingStageIndex,
    setCardProcessingStageIndex,
    mpReady,
    setMpReady,
    showToast,
    phoneInputRef,
    cardFormRef,
    cardSubmitInFlightRef,
    pixAutoRefreshByPaymentRef,
    pixFailureStatusRef,
    cardFailureStatusRef,
    mpInitToastShownRef,
    voucherRef,
    setIsVoucherOpen,
    identityCpfAttempts,
    setIdentityCpfAttempts,
    setIdentityWelcomeCountdown,
    identitySecuritySessionId,
    setIdentitySecuritySessionId,
    setIdentityCaptchaPrompt,
    identityCaptchaToken,
    setIdentityCaptchaToken,
    identityCaptchaAnswer,
    setIdentityCaptchaAnswer,
    setIdentityGuardNotice,
    isVerifyingClientCpf,
    setIsVerifyingClientCpf,
    suggestedClient,
    setSuggestedClient,
  } = state;

  const {
    cep,
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    estado,
    setLogradouro,
    setNumero,
    setComplemento,
    setBairro,
    setCidade,
    useSuggestedAddress,
    addressMode,
    isAddressSearchModalOpen,
    setIsAddressSearchModalOpen,
    addressSearchQuery,
    setAddressSearchQuery,
    addressSearchResults,
    addressSearchLoading,
    displacementEstimate,
    displacementStatus,
    mapsQuery,
    hasSuggestedAddress,
    suggestedAddressSummary,
    addressComplete,
    displacementReady,
    closeAddressSearchModal,
    handleSelectAddressResult,
    handleSelectStudioLocation,
    handleSelectHomeVisitLocation,
    handleUseSuggestedAddress,
    handleChooseOtherAddress,
    handleSelectLocationAddressMode,
    handleLocationCepChange,
    handleLocationStateChange,
    handleCepLookup,
    resetLocationState,
    enforceStudioLocationOnly,
  } = usePublicBookingLocation({
    isHomeVisit,
    setIsHomeVisit,
    homeVisitAllowed: Boolean(selectedService?.accepts_home_visit),
    suggestedClient,
    showToast,
  });

  const {
    formattedPhoneDigits,
    isPhoneValid,
    normalizedCpfDigits,
    isCpfValid,
    normalizedClientEmail,
    isEmailValid,
    resolvedClientFullName,
    isIdentityNameReady,
    clientHeaderFirstName,
    totalPrice,
    selectedDateObj,
    suggestedClientPublicName,
    suggestedClientFirstName,
    suggestedClientInitials,
  } = usePublicBookingFlowDerived({
    clientPhone,
    clientCpf,
    clientEmail,
    clientName,
    clientFirstName,
    clientLastName,
    clientLookupStatus,
    selectedService,
    isHomeVisit,
    displacementFee: displacementEstimate?.fee ?? 0,
    date,
    suggestedClient,
  });

  const onlineCutoffBeforeCloseMinutes = resolvePositiveMinutes(publicBookingCutoffBeforeCloseMinutes, 60);
  const onlineLastSlotBeforeCloseMinutes = resolvePositiveMinutes(publicBookingLastSlotBeforeCloseMinutes, 30);

  const {
    availableSlots,
    handleChangeMonth,
    handleSelectDay,
    isDayDisabled,
    isLoadingDaySlots,
    resetAvailability,
  } = usePublicBookingAvailability({
    activeMonth,
    date,
    enabled: Boolean(selectedService?.id),
    isHomeVisit,
    onlineCutoffBeforeCloseMinutes,
    onlineLastSlotBeforeCloseMinutes,
    selectedServiceId: selectedService?.id ?? null,
    setActiveMonth,
    setDate,
    setSelectedTime,
    tenantId: tenant.id,
  });

  const {
    handleVerifyExistingClientCpf,
    handleSwitchAccount,
    handleIdentityPhoneChange,
    handleIdentityCpfChange,
    handleIdentityCaptchaAnswerChange,
    handleNewClientFirstNameChange,
    handleNewClientLastNameChange,
    resetIdentityState,
  } = usePublicBookingIdentity({
    tenantId: tenant.id,
    step,
    formattedPhoneDigits,
    isPhoneValid,
    normalizedCpfDigits,
    isCpfValid,
    clientLookupStatus,
    suggestedClient,
    identityCpfAttempts,
    identitySecuritySessionId,
    identityCaptchaToken,
    identityCaptchaAnswer,
    isVerifyingClientCpf,
    clientFirstName,
    clientLastName,
    showToast,
    setStep,
    setSelectedService,
    setIsHomeVisit,
    resetAvailability,
    resetLocationState,
    phoneInputRef,
    setClientLookupStatus,
    setSuggestedClient,
    setClientName,
    setClientFirstName,
    setClientLastName,
    setClientEmail,
    setClientPhone,
    setClientCpf,
    setAcceptPrivacyPolicy,
    setAcceptTermsOfService,
    setAcceptCommunicationConsent,
    setIdentityCpfAttempts,
    setIdentityWelcomeCountdown,
    setIdentitySecuritySessionId,
    setIdentityCaptchaPrompt,
    setIdentityCaptchaToken,
    setIdentityCaptchaAnswer,
    setIdentityGuardNotice,
    setIsVerifyingClientCpf,
  });

  const {
    payableSignalAmount,
    pixQrExpired,
    pixRemainingLabel,
    pixProgressPct,
    isMercadoPagoMinimumInvalid,
    showCardProcessingOverlay,
    currentCardProcessingStage,
  } = usePublicBookingPaymentUi({
    totalPrice,
    signalPercentage,
    pixPayment,
    pixNowMs,
    step,
    paymentMethod,
    cardStatus,
    cardAwaitingConfirmation,
    cardProcessingStageIndex,
  });

  const clearCardSdk = useCallback(() => {
    try {
      cardFormRef.current?.unmount?.();
    } catch {
      // ignore sdk teardown errors
    }
    cardFormRef.current = null;
    cardSubmitInFlightRef.current = false;
  }, [cardFormRef, cardSubmitInFlightRef]);

  const { ensureAppointment, handleCopyPix, handleCreatePix, handleSelectPayment, handleReset } =
    usePublicBookingPaymentFlow({
      tenantId: tenant.id,
      tenantSlug: tenant.slug,
      selectedService,
      step,
      date,
      selectedTime,
      resolvedClientFullName,
      clientFirstName,
      clientLastName,
      clientPhone,
      normalizedClientEmail,
      clientCpf,
      isHomeVisit,
      cep,
      logradouro,
      numero,
      complemento,
      bairro,
      cidade,
      estado,
      displacementEstimate,
      isEmailValid,
      isPhoneValid,
      appointmentId,
      setAppointmentId,
      protocol,
      setProtocol,
      setIsSubmitting,
      pixPayment,
      setPixPayment,
      pixAttempt,
      setPixAttempt,
      pixStatus,
      setPixStatus,
      setPixError,
      setPixNowMs,
      pixQrExpired,
      paymentMethod,
      setPaymentMethod,
      payableSignalAmount,
      setCardStatus,
      setCardError,
      setCardAwaitingConfirmation,
      showCardProcessingOverlay,
      setCardProcessingStageIndex,
      setIsVoucherOpen,
      resetIdentityState,
      showToast,
      cardProcessingStagesLength: cardProcessingStages.length,
      cardFormRef,
      cardSubmitInFlightRef,
      pixAutoRefreshByPaymentRef,
      onClearCardSdk: clearCardSdk,
    });

  usePublicBookingPaymentEffects({
    step,
    paymentMethod,
    appointmentId,
    tenantId: tenant.id,
    pixPayment: pixPayment ? { id: pixPayment.id } : null,
    cardAwaitingConfirmation,
    showToast,
    setStep,
    setPixStatus,
    setPixError,
    setCardAwaitingConfirmation,
    setCardStatus,
    setCardError,
    pixFailureStatusRef,
    cardFailureStatusRef,
    cardFormRef,
    cardSubmitInFlightRef,
    mpInitToastShownRef,
    mercadoPagoPublicKey: mercadoPagoPublicKey ?? null,
    mpReady,
    payableSignalAmount,
    selectedService,
    ensureAppointment,
    normalizedClientEmail,
    resolvedClientFullName,
    clientPhone,
  });

  const { voucherBusy, handleDownloadVoucher, handleShareVoucher } = usePublicBookingVoucherActions({
    protocol,
    showToast,
    voucherRef,
  });

  const { showFooter, showNextButton, isNextDisabled, nextLabel, handleBack, handleNext } =
    usePublicBookingNavigation({
      step,
      setStep,
      isSubmitting,
      isPhoneValid,
      clientLookupStatus,
      isEmailValid,
      isCpfValid,
      isIdentityNameReady,
      acceptPrivacyPolicy,
      acceptTermsOfService,
      acceptCommunicationConsent,
      selectedServiceId: selectedService?.id ?? null,
      date,
      selectedTime,
      addressComplete,
      displacementReady,
      paymentMethod,
      isMercadoPagoMinimumInvalid,
    });

  const { handleServiceSelect, handleTalkToFlora } = usePublicBookingServiceActions({
    whatsappNumber,
    setSelectedService,
    setSelectedTime,
    setStep,
    setPaymentMethod,
    setPixPayment,
    setCardStatus,
    setProtocol,
    setAppointmentId,
    enforceStudioLocationOnly,
    showToast,
  });

  return {
    state,
    cep,
    logradouro,
    numero,
    complemento,
    bairro,
    cidade,
    estado,
    setLogradouro,
    setNumero,
    setComplemento,
    setBairro,
    setCidade,
    useSuggestedAddress,
    addressMode,
    isAddressSearchModalOpen,
    setIsAddressSearchModalOpen,
    addressSearchQuery,
    setAddressSearchQuery,
    addressSearchResults,
    addressSearchLoading,
    displacementEstimate,
    displacementStatus,
    mapsQuery,
    hasSuggestedAddress,
    suggestedAddressSummary,
    addressComplete,
    displacementReady,
    closeAddressSearchModal,
    handleSelectAddressResult,
    handleSelectStudioLocation,
    handleSelectHomeVisitLocation,
    handleUseSuggestedAddress,
    handleChooseOtherAddress,
    handleSelectLocationAddressMode,
    handleLocationCepChange,
    handleLocationStateChange,
    handleCepLookup,
    formattedPhoneDigits,
    isPhoneValid,
    normalizedCpfDigits,
    isCpfValid,
    normalizedClientEmail,
    isEmailValid,
    resolvedClientFullName,
    isIdentityNameReady,
    clientHeaderFirstName,
    totalPrice,
    selectedDateObj,
    suggestedClientPublicName,
    suggestedClientFirstName,
    suggestedClientInitials,
    availableSlots,
    handleChangeMonth,
    handleSelectDay,
    isDayDisabled,
    isLoadingDaySlots,
    handleVerifyExistingClientCpf,
    handleSwitchAccount,
    handleIdentityPhoneChange,
    handleIdentityCpfChange,
    handleIdentityCaptchaAnswerChange,
    handleNewClientFirstNameChange,
    handleNewClientLastNameChange,
    payableSignalAmount,
    pixQrExpired,
    pixRemainingLabel,
    pixProgressPct,
    isMercadoPagoMinimumInvalid,
    showCardProcessingOverlay,
    currentCardProcessingStage,
    ensureAppointment,
    handleCopyPix,
    handleCreatePix,
    handleSelectPayment,
    handleReset,
    voucherBusy,
    handleDownloadVoucher,
    handleShareVoucher,
    showFooter,
    showNextButton,
    isNextDisabled,
    nextLabel,
    handleBack,
    handleNext,
    handleServiceSelect,
    handleTalkToFlora,
    setMpReady,
  };
}
